### ISSUE TITLE
go get errors

### ISSUE THREAD

**Issue by kmulvey** [kavu/go-phash#1]
```
scratch (master)> go get github.com/kavu/go-sigstats
scratch (master)> go get github.com/kavu/go-phash
# pkg-config --cflags pHash
Package pHash was not found in the pkg-config search path.
Perhaps you should add the directory containing `pHash.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pHash' found
pkg-config: exit status 1
```

**Comment by kavu** [comment]
Hi Kevin!

What system do you have? If Linux, which distribution?

**Comment by kmulvey** [comment]
Fedora release 21 (Twenty One)
4.0.0-rc1+ 

also happens on 3.18.9-200.fc21.x86_64

**Comment by kavu** [comment]
Kernel version is not a big deal.

In order to install go-phash you need to install devel and .so lib files of the pHash lib itself http://www.phash.org/. Something like http://www.rpmseek.com/rpm-pl/libphash-devel.html?hl=com&cs=phash:PN:0:0:0:0:0 I am not a RPM person, so I could not help you more.

The reason you need this is the fact, that go-phash is a CGO wrapper around native C++ library.

**Comment by kmulvey** [comment]
yep that and CImg-devel did it, thanks
